# Generated by Django 5.0.3 on 2024-03-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_visable',
        ),
    ]
