# Generated by Django 5.0.3 on 2024-03-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
